version: '3.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: interview
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306